version: '3'
services:
  db:
    build: docker/db
    image: "ramann/bitstreamvpn:db"
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
  webapp:
    build: .
    image: "ramann/bitstreamvpn:webapp"
    command: "java -Xms2048m -Dkeystore.location=server.keystore -Dspring.datasource.url=jdbc:mysql://db:3306/test1 -Dipsec.datasource.url=jdbc:mysql://db:3306/testipsecdb -jar webapp-0.1.0.jar"
    ports:
      - 8080:8080
  bitcoin:
    build: docker/bitcoin
    image: "ramann/bitstreamvpn:bitcoin"
    command: "-port=18333 -rpcport=18332 -rpcuser=alice -rpcpassword=alicepass -rpcallowip=172.0.0.0/8 -connect=172.18.0.1:19444 -regtest -server -listen -debug -walletnotify=\"/home/bitcoin/walletnotify.sh %s webapp\" -reindex --blocknotify=\"/home/bitcoin/blocknotify.sh webapp\""
  strongswan:
    build: docker/strongswan
    image: "ramann/bitstreamvpn:strongswan"
    privileged: true
    ports:
      - 500:500/udp
      - 4500:4500/udp
